# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bYtVGJVrwsX4mh80PNrSsNI3a2JHdN94
"""

!pip install pymupdf chromadb sentence-transformers groq -q

from google.colab import files
import fitz
import pandas as pd
import subprocess
import io

# Install OCR — run this and wait for it to finish before anything else
print("Installing OCR tools... (takes ~30 seconds)")
subprocess.run(["apt-get", "install", "-y", "tesseract-ocr", "tesseract-ocr-eng"],
               capture_output=True)
subprocess.run(["pip", "install", "pytesseract", "Pillow", "-q"],
               capture_output=True)
import pytesseract
from PIL import Image
print("OCR ready.")

# Upload
uploaded = files.upload()
filename = list(uploaded.keys())[0]
print(f"\nUploaded: {filename}")

def extract_chunks(filepath):
    ext = filepath.split(".")[-1].lower()

    if ext == "pdf":
        doc = fitz.open(filepath)
        chunks = []
        total_pages = len(doc)
        print(f"PDF has {total_pages} pages — processing...")

        for i, page in enumerate(doc):
            print(f"Processing page {i+1}/{total_pages}...", end=" ")

            # Try normal text extraction first
            text = page.get_text().strip()

            # If empty — scanned page, use OCR
            if not text:
                try:
                    pix = page.get_pixmap(dpi=200)
                    img = Image.open(io.BytesIO(pix.tobytes("png")))
                    text = pytesseract.image_to_string(img).strip()
                    print(f"OCR → {len(text.split())} words")
                except Exception as e:
                    print(f"OCR failed: {e}")
                    text = ""
            else:
                print(f"text → {len(text.split())} words")

            if text:
                chunks.append(f"Page {i+1}:\n{text}")

        doc.close()
        return chunks

    elif ext == "csv":
        df = pd.read_csv(filepath)
        return chunk_dataframe(df)

    elif ext in ["xlsx", "xls"]:
        df = pd.read_excel(filepath)
        return chunk_dataframe(df)

    else:
        print("Unsupported file type.")
        return []

def chunk_dataframe(df):
    chunks = []
    summary = f"This dataset has {len(df)} rows and {len(df.columns)} columns.\n"
    summary += f"Columns: {', '.join(df.columns.tolist())}\n"
    summary += f"Sample data (first 3 rows):\n{df.head(3).to_string(index=False)}"
    chunks.append(summary)

    for i, row in df.iterrows():
        row_text = " | ".join([f"{col}: {val}" for col, val in row.items()])
        chunks.append(row_text)

        if (i + 1) % 10 == 0:
            batch = df.iloc[max(0, i-9):i+1]
            batch_summary = f"Rows {i-8} to {i+1} summary:\n{batch.to_string(index=False)}"
            chunks.append(batch_summary)

    return chunks

# Run extraction
chunks = extract_chunks(filename)
print(f"\nTotal chunks created: {len(chunks)}")

if len(chunks) > 0:
    print(f"\nFirst chunk preview:\n{chunks[0][:300]}...")
if len(chunks) > 1:
    print(f"\nSecond chunk preview:\n{chunks[1][:200]}...")
else:
    print("\nOnly 1 chunk — small or single page document")

import chromadb
from chromadb.utils import embedding_functions

embed_fn = embedding_functions.SentenceTransformerEmbeddingFunction(
    model_name="all-MiniLM-L6-v2"
)

client = chromadb.Client()

# Fix for stale answers — delete old collection if it exists
try:
    client.delete_collection("my_documents")
    print("Cleared previous collection")
except:
    pass

# Fresh collection every time
collection = client.get_or_create_collection(
    name="my_documents",
    embedding_function=embed_fn
)

# Add in batches — avoids memory issues with large files
batch_size = 100
for i in range(0, len(chunks), batch_size):
    batch = chunks[i:i+batch_size]
    collection.add(
        documents=batch,
        ids=[f"chunk_{j}" for j in range(i, i+len(batch))]
    )
    print(f"Stored chunks {i} to {i+len(batch)-1}...")

print(f"\nDone — {collection.count()} chunks ready to query!")

from google.colab import userdata
from groq import Groq

groq_client = Groq(api_key=userdata.get("test101"))

def ask(question, n_results=5):  # increased from 3 to 5
    results = collection.query(
        query_texts=[question],
        n_results=min(n_results, collection.count())
    )
    context = "\n\n".join(results["documents"][0])

    prompt = f"""Answer the question using ONLY the context below.
Be specific — use exact numbers and values from the data.
If the answer isn't in the context, say "I don't have that information."

Context:
{context}

Question: {question}
Answer:"""

    response = groq_client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}],
        max_tokens=400
    )
    return response.choices[0].message.content

# Test
print(ask("How many Males are from United States and their average age?"))
print("\n---\n")
print(ask("What are my skills?"))
print("\n---\n")
print(ask("What is FDE?"))

